volumes:
  mysql-volume:

services:
  web:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./:/src

  app:
    container_name: php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/src

  db:
    container_name: mysql
    image: mysql:8.0.37
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./docker/mysql/my.conf:/etc/my.conf
